// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.6. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IGatekeeper {
    struct DropIdTokenIdPair {
        uint256 dropId;
        uint256 tokenId;
    }

    function admin() external view returns (address);

    function createNormalGate(string memory _name, address _owner) external;

    function createRentedGate(
        uint256 _totalKeys,
        string memory _name,
        string memory _symbol
    ) external;

    function createSoulBoundGate(uint256 _totalKeys) external;

    function setTemplates(
        address _soulBoundKeyTemplate,
        address _rentedKeyTemplate
    ) external;

    function updateTenantData(
        uint256 _gateId,
        uint256 _tokenId,
        address tenant
    ) external;

    function updateUserData(
        uint256 _gateId,
        uint256 _tokenId,
        address _user
    ) external;

    function whitelistUsingNormalKey(uint256 _id) external;
}
